### ISSUE TITLE
Cannot mkdir: No space left on device

### ISSUE THREAD

**Issue by liuxiaopiao** [goldmann/docker-squash#103]
When I use the docker squash to reduce my docker image size with the command "docker save <image id> | sudo docker-squash -t newtag | docker load",  I met the problem such like 
tar: home/work_87586/dbzip_shiphome: Cannot mkdir: No space left on device

Here is the details info of my container(which run from the image which I want to reduce size) 
[root@f7ece211a2c8 /]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/loop0      100G   29G   71G  29% /
tmpfs           7.3G     0  7.3G   0% /dev
shm              64M     0   64M   0% /dev/shm
tmpfs           7.3G     0  7.3G   0% /sys/fs/cgroup
/dev/loop0      100G   29G   71G  29% /etc/hosts

How can i fix this kind of problem?

**Comment by goldmann** [comment]
You use the tool in a wrong way. We do not support piping. Please take a look at README for example invocation.

The `save` and `load` commands are executed by the tool internally.

**Comment by liuxiaopiao** [comment]
Thanks @goldmann for the reply. But I got this info from https://github.com/jwilder/docker-squash:
You can reduce disk IO by piping the input and output to and from docker:
$ docker save <image id> | sudo docker-squash -t newtag | docker load

Why is this wrong?

**Comment by liuxiaopiao** [comment]
Even if i use the commands which is not pipe:
$ docker save c2192e054560 image.tar
$ sudo docker-squash -i image.tar -o squashed.tar

Still have the same problem 
tar: var/tmp/.oracle: Cannot mkdir: No such file or directory
tar: Exiting with failure status due to previous errors
