### ISSUE TITLE
Symlink in newer layer overwritten by contents in base layer (1.04)

### ISSUE THREAD

**Issue by erydo** [goldmann/docker-squash#124]
I have a base image that starts with three normal files, say `A`, `B`, and `C`. The contents of these files each say "Implement me!".

A derived image overrides the contents of one of those files and replaces the other files with symlinks. With normal `docker build`, the contents of that derived image are as expected:

```
A (normal file): "Worked"
B (symlink to A): "Worked"
C (symlink to A): "Worked"
```

When running `docker-squash` version `1.04`, the contents are incorrect. The symlinks that were added are removed and the base image's contents are incorrectly preserved in their place:

```
A (normal file): "Worked"
B (normal file): "Implement me!"
C (normal file): "Implement me!"
```

**Comment by goldmann** [comment]
Let me try to reproduce it. Hold on.

**Comment by goldmann** [comment]
I think I need to understand it a bit more, please take a look at the https://github.com/goldmann/docker-squash/commit/2524505107e254bd1d702d13bf9e408629182f01 commit. I created there an integration test that should hopefully do what you described I even extended the test suite to make sure the files are symlinks and content of these files is what it should be. If you spot an issue - let me know!

I squashed last 3 layers and tried to squash the whole image - both worked fine for me, so I'm puzzled now.

**Comment by goldmann** [comment]
Ping @erydo.

**Comment by goldmann** [comment]
Closing.
