### ISSUE TITLE
Can't Find Squashed Image

### ISSUE THREAD

**Issue by RiteshAdobe** [goldmann/docker-squash#129]
hi,
I am running this command and the image is said to be loaded but upon firing docker images command, the image doesn't show up!.Please help as to how can i find my image!

Logs are -

Done. New image created.
  -  1dceaf3dac2f 292.471209 years  351.6 MB
  -  38dfe678b216 About a minute /bin/sh -c #(squash) from 1dceaf3dac2f 1.378 GB
Removing tempdir /apps/temp/docker-squash566257163
Loaded image ID: sha256:16c135c42f0e1df483d02989d482b9ac75fa17618fd7926f26e214062492eeaa

However, docker images DOESN'T SHOW 38dfe678b216 !

Please help!

**Comment by goldmann** [comment]
Please show me the command you run.

**Comment by RiteshAdobe** [comment]
docker save 16c135c42f0e | TMPDIR=/apps/temp/ docker-squash -t ruby_base_import_squashed -verbose | docker load

**Comment by goldmann** [comment]
Please read `docker-squash --help` or see examples in readme. You are not invoking it in proper way.

**Comment by RiteshAdobe** [comment]
Ok,

I ran - docker-squash -verbose -from 475e268eb98e -t docker2-est-registry-local.dr.corp.adobe.com/base/apps/test/skehmet_squash:squashed ruby_base

And the process is hung after logging - 
Loading export from STDIN using /tmp/docker-squash485659790 for tempdir

Is this expected?

**Comment by goldmann** [comment]
Again, please read carefully how you run the tool. You use single minus signs (`-`) for long arguments where you should  use double minus signs (`--`):

```
docker-squash --verbose --from 475e268eb98e -t docker2-est-registry-local/base/apps/test/skehmet_squash:squashed ruby_base
```

**Comment by RiteshAdobe** [comment]
Thanks!..

Can u please help as to why i am unable to pass TMP_DIR in the command?
It says it's not proper.

**Comment by goldmann** [comment]
We do not expose this environment variable, please use `--tmp-dir` argument.

**Comment by RiteshAdobe** [comment]
ok,

I had fired the command but it;s hung after logging -
Loading export from STDIN using /tmp/docker-squash767364479 for tempdir

It's almost 45 minutes. Is it expected or is there any error?

Also, should be push the final image to registry, for as of now i am trying to store it locally. Is it fine?

sorry for bothering you so much :)

**Comment by goldmann** [comment]
Please paste the whole log so I can see what;s going on and how you invoked the tool.

Image is stored locally in Docker daemon by default. Later you can push it to registry if you want.

**Comment by RiteshAdobe** [comment]
[root@no1010042211085 squash]# docker-squash --verbose  --from 475e268eb98e -t ruby_base_squashed:squashed  ruby_base
Loading export from STDIN using /tmp/docker-squash767364479 for tempdir

This is all i have currently on screen!

**Comment by goldmann** [comment]
Please change `--from` to `--from-layer` or `-f`.

**Comment by RiteshAdobe** [comment]
It's not accepting!

[root@no1010042211085 squash]# docker-squash --verbose  --from-layer 475e268eb98e -t ruby_base_squashed:squashed  ruby_base
flag provided but not defined: -from-layer

Usage: docker-squash [options]

Squashes the layers of a tar archive on STDIN and streams it to STDOUT

Options:
  -from string
        Squash from layer ID (default: first FROM layer)
  -i string
        Read from a tar archive file, instead of STDIN
  -keepTemp
        Keep temp dir when done. (Useful for debugging)
  -o string
        Write to a file, instead of STDOUT
  -t string
        Repository name and tag for new image
  -v    Print version information and quit
  -verbose
        Enable verbose logging

**Comment by goldmann** [comment]
You are using https://github.com/jwilder/docker-squash, not my tool...

**Comment by RiteshAdobe** [comment]
Many thanks!

Now getting the following error - 

[root@no1010042211127 apps]# docker-squash --tmp-dir /apps/tmp/ -f 10 -t ruby:squashed e2be970be822
2016-10-06 14:00:26,871 root         INFO     docker-squash version 1.0.4, Docker 23cf638, API 1.24...
2016-10-06 14:00:26,872 root         INFO     Using v2 image format
2016-10-06 14:00:26,872 root         ERROR    Preparing temporary directory failed
2016-10-06 14:00:26,872 root         ERROR    Execution failed, consult logs above. If you think this is our fault, please file an issue: https://github.com/goldmann/docker-squash/issues, thanks!


Please help!

**Comment by goldmann** [comment]
Run it with `-v` to get verbose logs.

**Comment by RiteshAdobe** [comment]
Hi,

Upon running this tool for the first time, i always get this error -


[root@no1010042211127 ~]# docker-squash --tmp-dir /apps/tmp/ -f 3c65cb5885a4 -t sekhmet:squashed sekmet_full:latest
2016-10-07 05:35:35,704 root         INFO     docker-squash version 1.0.4, Docker 23cf638, API 1.24...
2016-10-07 05:35:35,705 root         INFO     Using v2 image format
2016-10-07 05:35:35,706 root         ERROR    Preparing temporary directory failed
2016-10-07 05:35:35,706 root         ERROR    Execution failed, consult logs above. If you think this is our fault, please file an issue: https://github.com/goldmann/docker-squash/issues, thanks!


Please check!

**Comment by goldmann** [comment]
I'll repeat what I said above: Run it with `-v` to get verbose logs so I can help you. I don't know the root case.
