### ISSUE TITLE
Squash.run() can return different image ID than docker uses for loaded image

### ISSUE THREAD

**Issue by twaugh** [goldmann/docker-squash#130]
When running against docker 1.10, Squash().run() returns the config digest it calculated for the JSON describing the image.

I have seen (but don't have exact details of) an occasion where this returned image ID differed from image ID advertised by docker after loading the image.

My suggestion: Squash().run() could return None when handling v2 images, to indicate that it cannot be sure of the image ID docker will use for this image.

**Comment by goldmann** [comment]
After some investigation I couldn't reproduce the issue. Generated ID seems to be correct. It is indeed the sha256sum of the JSON file descriptor content of the image. I tried to load it back to Docker and it shows under the calculated ID. I guess at this point we need a reproducer where the image ID differs.

**Comment by twaugh** [comment]
Agreed. In trying to find this reproducer I think I found the real culprit: pushing an image to a registry that does not support v2 schema 2, then pulling the image from that registry, results in an image with a different image ID.

This issue can be closed.

**Comment by goldmann** [comment]
Oh, yes, this could be the issue. Thanks!
