### ISSUE TITLE
Password getting revealed in docker history

### ISSUE THREAD

**Issue by RiteshAdobe** [goldmann/docker-squash#138]
Hi,

We are squashing our docker image using your tool and it is working fine. The only security vulnerability we are facing is that upon using DOCKER HISTORY command , we can see our artifactory password  , which we are passing through build arguments using BUILD-ARG , getting revealed in the final ONE-LAYERED image. 

Can you please guide if it is possible to selectively squash layers or any other way to get around with this?

Thanks

**Comment by rolweber** [comment]
Surely your password is also revealed by the history of the unsquashed image.
So that is not a problem of the docker-squash tool, but of Docker in general.
See also https://github.com/docker/docker/issues/13490

**Comment by RiteshAdobe** [comment]
Yeah that's true, but if we use Docker import-export command , then we can very well get off this thing.
isn't it?

**Comment by rolweber** [comment]
The Dockerfile reference warns about using `--build-args` for secrets, because the values appear in the history: https://docs.docker.com/engine/reference/builder/#/arg

So you'd like an option to hide the original history in the squashed image? That might indeed plug the hole left open by Docker.

**Comment by rolweber** [comment]
`--build-arg` values also become part of Docker cache keys. There might be internal data structures besides the history that still expose your password.

**Comment by RRAlex** [comment]
Is it really a hole if the password is in clear in the image anyway?

**Comment by rolweber** [comment]
The `--build-arg` values for ARG variables are accessible at build time to RUN commands. But unlike ENV variables, they don't become part of the image automatically. I assume that the password is only used at build time to download artifacts into the image. But there's no guarantee from Docker that the values of ARG variables are recorded only in the history and not in other places as well.

**Comment by goldmann** [comment]
I'll close this ticket as it is not related directly to docker-squash but to Docker itself.
