### ISSUE TITLE
Docker for Python API dependency is out of date

### ISSUE THREAD

**Issue by linuxfreakus** [goldmann/docker-squash#139]
The Docker for Python API is currently being required as `docker-py` which was last used in version `1.10.6`.

Newer versions are now called `docker` and currently it is up to version `2.1.0` and since they both are called `docker` when you import them you can't have both versions at the same time so I'm starting to run into issues with this conflict since there are some structural API changes.

I looked at the code and it appears as if the changes needed are minimal.

**Comment by goldmann** [comment]
Oh, yeah, thanks for letting me know. I'll fix this early next week!

**Comment by goldmann** [comment]
I've added my proposal as #143.
