### ISSUE TITLE
stdout/stderr

### ISSUE THREAD

**Issue by brubbel** [goldmann/docker-squash#144]
Hi, it seems that docker-squash is using the stderr stream to provide info messages.
However this breaks automated build systems, which rely on stderr to detect actual errors.
Is this intended behaviour?
Thanks for checking.

Name: docker-squash
Version: 1.0.5 (from pip)

**Comment by goldmann** [comment]
That is a surprising info. How do you execute it? Can you give me some output that is redirected to stderr?

**Comment by brubbel** [comment]
docker-squash my/image -t my/squashed-image 2>/dev/null
In my version, docker-squash will run silent until finished.

**Comment by goldmann** [comment]
I can confirm this. I'll take a look, thanks!

**Comment by goldmann** [comment]
It looks that the `StreamHandler` by default writes to stderr: https://docs.python.org/2/library/logging.handlers.html#logging.StreamHandler This is an easy fix.

**Comment by brubbel** [comment]
If possible, can you also publish this fix to PyPI later on? Thanks for the fast solution!

**Comment by goldmann** [comment]
Yes, definitely. This will be part of `1.0.6` release. I do plan to add a few other issues to this release.
