### ISSUE TITLE
command 'docker-squash IMAGE_NAME' doesn't re-tag IMAGE_NAME

### ISSUE THREAD

**Issue by praiskup** [goldmann/docker-squash#151]
According to docker-squash --help ..
```
  -t TAG, --tag TAG     Specify the tag to be used for the new image. by
                        default it'll be set to 'image' argument
```
.. the new docker image should be tagged to IMAGE_NAME;  but it doesn't happen now -- one needs to use:

```bash
docker IMAGE_NAME -t IMAGE_NAME
```

**Comment by goldmann** [comment]
Ooops, that help page is wrong, sorry about that! If `-t` is not set, it'll not add any tags.
