### ISSUE TITLE
Tag a release which includes update for 'docker-py' library

### ISSUE THREAD

**Issue by TheFriendlyCoder** [goldmann/docker-squash#154]
I recently hit a problem where I am writing some Docker scripts which make use of the 'docker' Python library. These scripts were working well, until I added a new dependenc on the docker-squash project herer. The problem being that the latest package of 'docker-squash' on PyPI has a transitive dependency on the 'docker-py' project... and apparently 'docker-py' and 'docker' are incompatible copies of the same library which conflict with one another when installed in the same environment.

Given that the latter package, 'docker' is the most recent version this library should be updated to make use of that one. Based on my quick review of the latest revision of your project it would seem the sources have already been updated to reflect this new dependency but no one has yet released a new version with that fix on PyPI.

As such I'd like to ask that someone prepare a release sooner rather than later to avoid this problem.

**Comment by goldmann** [comment]
I've just tagged 1.0.6. It's released on PyPI.
