### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by lad** [goldmann/docker-squash#173]
This issue has been open for a year and I hit the same problem today:

https://github.com/goldmann/docker-squash/issues/147

Given the open issues not being addressed, could you please mark this project as abandoned if you don't intend to fix issues.

**Comment by goldmann** [comment]
It is not, latest release was done 17 days ago.

**Comment by lad** [comment]
I was overly harsh, my apologies. Thanks for putting this out.
