### ISSUE TITLE
ERROR    'config'

### ISSUE THREAD

**Issue by tico-tico** [goldmann/docker-squash#174]
My private project, running on Gitlab.com shared worker, suddenly stop working.
Basically it uses Opensuse Tumbleweed base image, installs various stuff on it and squashes before pushing container (or image? never understand how to call it properly) to the registry.
Last time I tried (~2 months ago) everything was OK.
There are some exceptions in the end of the log.

[docker-squash.txt](https://github.com/goldmann/docker-squash/files/2787265/docker-squash.txt)

**Comment by goldmann** [comment]
It looks like you're using Docker CE 18.09.1 and it looks that the tarfile generated by this version is incompatible with what we expect. To make it work I can only suggest downgrading Docker version.

**Comment by tico-tico** [comment]
Hm, It's just the default image from the dockerhub *docker:stable*.
Interesting thing that my other project based on Alpine squashed without any problems.

OK, I'll try to use the older docker image to fix my issue. Will report here.

**Comment by goldmann** [comment]
See what Docker daemon was used last time it passed.

**Comment by tico-tico** [comment]
Nice idea, i should have done it myself, sorry. There's no info on version in the logs, but API is 1.39.

```
2018-11-14 07:53:00,373 root         INFO     docker-squash version 1.0.7, Docker 4d60db4, API 1.39...
2018-11-14 07:53:00,374 root         INFO     Using v2 image format
2018-11-14 07:53:00,383 root         INFO     Old image has 11 layers
```

**Comment by goldmann** [comment]
This translates to `18.09.0`.

**Comment by tico-tico** [comment]
Just switched to another base image. Squashing works with *opensuse/leap:latest*, so it seems like *opensuse/tumbleweed:latest* is causing the troubles.

**Comment by goldmann** [comment]
Closing this issue.
