### ISSUE TITLE
Large docker image 

### ISSUE THREAD

**Issue by nitdana** [goldmann/docker-squash#197]
Hi,

First - this tool is awesome and very useful, giving us so much value, just wanted you to know it.
Recently I tried to run it on a very large image of 6 GB, and it took 4 hours to squash it.
Is there anything I can do to for optimizing this process? anyway to run it on multiple cpu maybe?

Thanks!

**Comment by goldmann** [comment]
Hey, thanks!

You may be interested in reading this: https://github.com/goldmann/docker-squash/issues/196 and this: https://github.com/goldmann/docker-squash/issues/63.

There are two things that holds us from being even more performant:

1. Docker daemon is single-threaded.
2. We compare files if these exist in layers - we cannot do this in parallel.

None of them are fixable currently.

**Comment by nitdana** [comment]
Got it, thanks!
