### ISSUE TITLE
docker-squash: command not found

### ISSUE THREAD

**Issue by za13** [goldmann/docker-squash#201]
on ubuntu18, I did

    pip3 install docker-squash

when I run it, I get

    docker-squash: command not found

even though it is in `~/local/bin`, and I added that to `$PATH`

**Comment by za13** [comment]
can anyone help?

**Comment by djsavvy** [comment]
You forgot a period --- your path is supposed to contain `~/.local/bin`, not `~/local/bin`.

**Comment by za13** [comment]
I changed it to `~/.local/bin` and got the same error

**Comment by zoidbergwill** [comment]
Did pip3 install it into ~/local/bin or ~/.local/bin?

Does running it with the full path work? e.g. `~/.local/bin/docker-squash` or `~/local/bin/docker-squash`?

**Comment by goldmann** [comment]
Generally speaking, you need to make sure the binary is on your `PATH`. Location of the binary depends what method of installation you used (pip, operating system packages, etc).

I'll close this issue now.
