### ISSUE TITLE
Default value for '--message' breaks v2 schema

### ISSUE THREAD

**Issue by janjagusch** [goldmann/docker-squash#220]
The default value for `--message` is `None`, which is not valid in the v2 Docker manifest schema and can lead to the following (or a similar) error when trying to push to a registry (tested with Quay):

```
image.docker.schema2.config.MalformedSchema2Config: config data does not match schema: None is not of type 'string'
Failed validating 'type' in schema['properties']['history']['items']['properties']['comment']:
    {'description': 'Comment describing the layer', 'type': 'string'}
On instance['history'][0]['comment']:
    None
```

I think there are two options here:
- Make `--message` a required argument.
- Set a more appropriate default (e.g. 'Squash layers with docker-squash.')

What do you think?

**Comment by rnc** [comment]
I agree but I think the problem is in cli.py where argparse is overriding the default empty string and passing a None through.
