### ISSUE TITLE
404 Client Error: Not Found ("Untar re-exec error: exit status 1

### ISSUE THREAD

**Issue by gcstang** [goldmann/docker-squash#80]
I found it when running on the branch you created for my last issue but it does the same in Master currently.

docker-squash -v -t hostname:5000/tomcat7:latest hostname:5000/tomcat7

[dockersquash04042016.txt](https://github.com/goldmann/docker-squash/files/202681/dockersquash04042016.txt)

**Comment by goldmann** [comment]
OK, this one is more interesting and is probably related to special files created by YUM. Most probably we're talking here about hard links.

I'll try to find a reproducer here.

Out of curiosity - why are you squashing **all** layers into single one? What's the use case for this?

**Comment by goldmann** [comment]
Found a similar problem: https://github.com/appc/docker2aci/issues/98

**Comment by goldmann** [comment]
I do have a reproducer now and I'm working on a fix.

**Comment by goldmann** [comment]
Could you please give `gh-80-untar-re-exec` a try? I think I fixed it.

**Comment by gcstang** [comment]
Thank you this seems to have worked.
After creating my images I'm trying to make them as small as possible for storage into a repository but without losing any ENV settings I added or CMD setting.  This seems to have solved my issue with ENV going away when I tried something like this command:
`docker export $(docker ps -a | grep <container id> |awk '{print $1}') | docker import - <new image name>`

So far the CMD setting I used in creating my images are not working after the docker-squash but I'm sure there is another way to run that possibly when creating a new container from my image.

I'm still really new to Docker so if there  is a better way please do share any information.

Thank you again for your help.

**Comment by goldmann** [comment]
You are correct that the metadata is removed when doing the `docker export` trick because this command exports only the content of the container, nothing else.

It seems you are stuck with tools like mine it seems :)

Thanks for reporting issues, your use case is a bit different from what I'm used to hear. Let me know if you hit any other issues.
