### ISSUE TITLE
Could this be enhanced to keep a certain number of layers.

### ISSUE THREAD

**Issue by rhatdan** [goldmann/docker-squash#90]
Would be nice if I could squash all layers except the first layers.

from rhel7
run
run 
label
environment

docker-squach --keep 1 ...

Then we end up with the new image containing two layers.  The rhel base image and all of the changes in the Dockerfile.

I think a tool like this renamed oci-squash, could be something we could think about shipping.

**Comment by goldmann** [comment]
This already implemented, somewhat. We do it from the other way: you can specify how many layer you want to squash. If you know the count of layers in the images, just specify `--from NUM_LAYERS-1`. This should work for you. Make sure you use latest RC, of course.

Other option if to read "FROM" form the Dockerfile and use this as the argument. This is basically what I do in my scripts.

**Comment by goldmann** [comment]
For example with: `awk '/^FROM/{print $2}' Dockerfile`

**Comment by rhatdan** [comment]
Perhaps there is not a great way to do this.  What I really need is a way of squashing everything in my docker build.  But maintaining layers that were in the From image.  Not sure if there is a way to figure this out.

**Comment by goldmann** [comment]
From the squash tool POV image is a bunch of layers. It has no idea what Dockerfiles were used to create it, thus we cannot be smart and by defaul squash latest Dockerfile. This would be preferable, but it's not really possible.

This means that the work of determining the correct layer to squash from needs to be done by the user. Like I mentioned above the simplest way is to parse Dockerfile and lookup the `FROM` instruction. This is what our team internally does on our CI, and even more - this is what we do in production.

**Comment by rhatdan** [comment]
Could we make the tool smart enough to say only squash to this layer, or even smarter have it look up the layer.

oci-squash --keep=rhel7 newimage

THen oci-squash could look into docker images to for rhel7 and stop squashing when it gets to the checksum.

**Comment by goldmann** [comment]
Like I sad above - I took the opposite direction - you need to say how many layers you want to squash (or from which layer to squash), not how many you want to keep.

But your example is very simple - you could say `docker-squash -f rhel7 -t newimage oldimage`. And it'll do what you want, which means leave the rhel7 layer alone and squash everything from that layer to the end.

**Comment by rhatdan** [comment]
Are you saying you have support for this or this is something we could do?

**Comment by goldmann** [comment]
Support for `-f rhel7` way of squashing is implemented since the beginning of this tool. Support for `-f N` for squashing last `N` layers is available since 1.0.0rc's.

So, yes, it's already there :)

**Comment by rhatdan** [comment]
Excellent.  I think we should look at making this part of the docker package.

Sadly I can not get it to build, on python3. On Rawhide here is what I get.

```
make
tox -- tests
GLOB sdist-make: /home/dwalsh/docker-squash/setup.py
py27 inst-nodeps: /home/dwalsh/docker-squash/.tox/dist/docker-squash-1.0.0.dev0.zip
py27 installed: coverage==4.0.3,docker-squash==1.0.0.dev0,funcsigs==1.0.2,mock==2.0.0,pbr==1.9.1,py==1.4.31,pytest==2.9.1,pytest-cov==2.2.1,six==1.10.0
py27 runtests: PYTHONHASHSEED='2663680645'
py27 runtests: commands[0] | py.test -v --cov-report term --cov-report html --cov docker_squash --basetemp=/home/dwalsh/docker-squash/.tox/py27/tmp --junit-xml target/junit-py27.xml --junit-prefix py27 tests
============================= test session starts ==============================
platform linux2 -- Python 2.7.11, pytest-2.9.1, py-1.4.31, pluggy-0.3.1 -- /home/dwalsh/docker-squash/.tox/py27/bin/python2.7
cachedir: .cache
rootdir: /home/dwalsh/docker-squash, inifile: 
plugins: cov-2.2.1
collected 9 items / 2 errors 

tests/test_unit_v2_image.py::TestReadingConfigFiles::test_should_read_json_file PASSED
tests/test_unit_v2_image.py::TestGeneratingMetadata::test_generate_image_metadata PASSED
tests/test_unit_v2_image.py::TestGeneratingMetadata::test_generate_image_metadata_without_any_layers_to_squash PASSED
tests/test_unit_v2_image.py::TestGeneratingMetadata::test_generate_manifest PASSED
tests/test_unit_v2_image.py::TestGeneratingMetadata::test_generate_squashed_layer_metadata PASSED
tests/test_unit_v2_image.py::TestGeneratingMetadata::test_generate_squashed_layer_path_id PASSED
tests/test_unit_v2_image.py::TestWritingMetadata::test_write_image_metadata PASSED
tests/test_unit_v2_image.py::TestWritingMetadata::test_write_manifest_metadata PASSED
tests/test_unit_v2_image.py::TestWritingMetadata::test_write_squashed_layer_metadata PASSED

----- generated xml file: /home/dwalsh/docker-squash/target/junit-py27.xml -----
--------------- coverage: platform linux2, python 2.7.11-final-0 ---------------
Name                            Stmts   Miss Branch BrPart  Cover
-----------------------------------------------------------------
docker_squash/__init__.py           2      0      0      0   100%
docker_squash/cli.py               48     48      6      0     0%
docker_squash/errors.py             4      0      0      0   100%
docker_squash/image.py            306    241     97      1    18%
docker_squash/lib/__init__.py       0      0      0      0   100%
docker_squash/lib/common.py        37     36      6      0     2%
docker_squash/lib/xtarfile.py      67     61     18      0    12%
docker_squash/squash.py            50     45     16      0     8%
docker_squash/v1_image.py          47     36      8      0    24%
docker_squash/v2_image.py         147     62     44     10    52%
docker_squash/version.py            1      0      0      0   100%
-----------------------------------------------------------------
TOTAL                             709    529    195     11    23%
Coverage HTML written to dir target/coverage-py27
==================================== ERRORS ====================================
_________________ ERROR collecting tests/test_integ_squash.py __________________
tests/test_integ_squash.py:6: in <module>
    import docker
E   ImportError: No module named docker
_________________ ERROR collecting tests/test_unit_v1_image.py _________________
tests/test_unit_v1_image.py:6: in <module>
    from docker_squash.squash import Squash
docker_squash/squash.py:9: in <module>
    from docker_squash.lib import common
docker_squash/lib/common.py:3: in <module>
    import docker
E   ImportError: No module named docker
====================== 9 passed, 2 error in 0.45 seconds =======================
ERROR: InvocationError: '/home/dwalsh/docker-squash/.tox/py27/bin/py.test -v --cov-report term --cov-report html --cov docker_squash --basetemp=/home/dwalsh/docker-squash/.tox/py27/tmp --junit-xml target/junit-py27.xml --junit-prefix py27 tests'
py34 create: /home/dwalsh/docker-squash/.tox/py34
ERROR: InterpreterNotFound: python3.4
___________________________________ summary ____________________________________
ERROR:   py27: commands failed
ERROR:   py34: InterpreterNotFound: python3.4
Makefile:4: recipe for target 'test' failed
make: *** [test] Error 1
[Exit 2]
```

**Comment by goldmann** [comment]
You did not install everything that's needed - in this case `python-docker-py` package.

Please note that this package is already available in Fedora since about a year now. This is the earlier version called python-docker-scripts https://bodhi.fedoraproject.org/updates/?packages=python-docker-scripts.

Recently this project was renamed to docker-squash and new builds of this package are available for Rawhide and for other versions: http://koji.fedoraproject.org/koji/packageinfo?packageID=22304. python-docker-squash obsoletes `python-docker-scripts`. Please note that `python-docker-squash` package wasn't submitted as an update yet for Fedora 22/23/24. This a matter of days, because I need to coordinate this with atomic-reactor guys.

There is a request to add it for EPEL 7 but I haven't looked at this.

Regarding tests - you can see them running for Docker 1.9 and 1.10 on py27 and py34 here: https://circleci.com/gh/goldmann/docker-squash

HTH

**Comment by rhatdan** [comment]
On 04/28/2016 01:58 PM, Marek Goldmann wrote:
>
> You did not install everything that's needed - in this case 
> |python-docker-py| package.
>
rpm -q python-docker-py
python-docker-py-1.8.0-3.fc25.noarch

> Please note that this package is already available in Fedora since 
> about a year now. This is the earlier version called 
> python-docker-scripts 
> https://bodhi.fedoraproject.org/updates/?packages=python-docker-scripts.
>
Cool.
>
> Recently this project was renamed to docker-squash and new builds of 
> this package are available for Rawhide and for other versions: 
> http://koji.fedoraproject.org/koji/packageinfo?packageID=22304. 
> python-docker-squash obsoletes |python-docker-scripts|. Please note 
> that |python-docker-squash| package wasn't submitted as an update yet 
> for Fedora 22/23/24. This a matter of days, because I need to 
> coordinate this with atomic-reactor guys.
>
I would prefer it called oci-squash...
>
> There is a request to add it for EPEL 7 but I haven't looked at this.
>
I was thinking more of adding this as a docker subpackage, as a 
supported image
>
> Regarding tests - you can see them running for Docker 1.9 and 1.10 on 
> py27 and py34 here: https://circleci.com/gh/goldmann/docker-squash
>
> HTH
>
docker-scripts3
Traceback (most recent call last):
   File "/usr/bin/docker-scripts3", line 9, in <module>
     load_entry_point('docker-scripts==1.0.0rc2', 'console_scripts', 
'docker-scripts')()
   File "/usr/lib/python3.5/site-packages/docker_scripts/cli.py", line 
105, in run
     cli.run()
   File "/usr/lib/python3.5/site-packages/docker_scripts/cli.py", line 
91, in run
     args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'

rpm -q python3-docker-scripts
python3-docker-scripts-1.0.0-0.2.rc2.fc25.noarch

**Comment by goldmann** [comment]
> I would prefer it called oci-squash...

Right, but the upstream tool is called docker-squash :) Additionally I recently did the rename, went trough Fedora package rename process, etc.

Like I said above - this tool was renamed from `docker-scripts` to `docker-squash`. I'm not sure why in Rawhide there is `python-docker-scripts` package available, because the `python-docker-squash` tool has proper obsoletes. I need to investigate this. Either case - you should use `python-docker-squash` package: http://koji.fedoraproject.org/koji/buildinfo?buildID=755386

If there is an issue with this package, please open a BZ ticket for it.

**Comment by jmtd** [comment]
Dan:
> I would prefer it called oci-squash...

What does oci mean/stand for in your preferred name?

**Comment by rhatdan** [comment]
Open Container Initiative.  https://www.opencontainers.org/

Basically docker image but outside the control of any one company.

**Comment by goldmann** [comment]
I'm closing this issue, because requested enhancement is basically already implemented.
