### ISSUE TITLE
Incorrect metadata causing image to fetch not squashed layers into image

### ISSUE THREAD

**Issue by lcarva** [goldmann/docker-squash#91]
```bash
$ docker --version
Docker version 1.9.1, build ee06d03/1.9.1
$ docker pull docker.io/jboss/wildfly:latest
...
$ docker history docker.io/jboss/wildfly:latest
... 21 layers listed
$ docker-squash -t jboss/wildfly:squashed docker.io/jboss/wildfly:latest
... Squashing 21 layers
$ docker history jboss/wildfly:squashed
.. 21 layers listed
```

By providing `-f 20`, the most recent 20 layers are squashed into one resulting in a total of 2 layers, as expected. However, using `-f 21` results in no layers being squashed at all.

1. Is it possible to squash all layers into a single layer? Or is two layers the minimum?
2. This seems to have been introduced by #59 . When from_layer is None, it uses the length of layers. Maybe this should be length of layers - 1 ?

CC @twaugh

**Comment by lcarva** [comment]
Previous behavior in 0.4.4 when from_layer is not provided was to use length of layers -1:

```bash
$ docker-scripts --version
0.4.4
$ docker-scripts squash -t jboss/wildfly:squashed docker.io/jboss/wildfly:latest                  
2016-05-18 16:46:12,380 root         INFO     Running version 0.4.4, Docker ee06d03/1.9.1, API 1.21...
2016-05-18 16:46:12,380 root         INFO     Squashing image 'docker.io/jboss/wildfly:latest'...
2016-05-18 16:46:12,425 root         INFO     Old image has 21 layers
2016-05-18 16:46:12,425 root         INFO     Attempting to squash from layer 1544084fad81e27c28a8c12c08b2439451fd1e74
5e38c1dcecd862d240c4235e...
2016-05-18 16:46:12,425 root         INFO     Checking if squashing is necessary...
2016-05-18 16:46:12,425 root         INFO     We have 20 layers to squash
```

**Comment by goldmann** [comment]
I tried your example, and this is what I got at the end:

```
$ docker history jboss/wildfly:squashed
IMAGE               CREATED             CREATED BY          SIZE                COMMENT
98f91f7d4272        40 seconds ago                          545.5 MB 
```

```
$ docker-squash --version                                                      
1.0.0rc4
```

```
$ docker --version
Docker version 1.10.3, build 667d6d1/1.10.3
```

I'll try one more time on older Docker.

**Comment by goldmann** [comment]
I can confirm that this is a bug when using v1 format (pre Docker 1.10), I'm going to fix it.

**Comment by goldmann** [comment]
This is a bit more complicated. When the image is created with Docker < 1.10, then everything works fine, but if it was created with Docker >= 1.10 then we see this issue. There is a conversion on the fly going from >= 1.10 image format to the previous one when you use older Docker daemon and you pull the image from a registry that supports newer format. I'm going now to investigate what is the difference between these images.

Additionally my integs didn't catch it (I need to tweak them a bit too), because the image I'm using for tests (`busybox:1.24.0`) was created with Docker 1.8.2 on HUB and wasn't rebuilt since then.

Funny issue, thanks for reporting it!

**Comment by goldmann** [comment]
Just one more note: if you build the image and then squash using the same Docker daemon - it'll not affect you. It affects images that are generated using new Docker, then imported into old Docker.

**Comment by goldmann** [comment]
Update after even more testing: Docker daemon used to build the image has nothing to do with the issue. You can see the issue if you fetch the image from HUB and execute squashing directly on it. If you do modify the image (for example by adding a new layer), then squashing will work as expected. Investigating even deeper now.

**Comment by goldmann** [comment]
I do have a fix locally for it, but I'm now looking if something else doesn't need to be updated.

**Comment by goldmann** [comment]
Could you please use the `gh-91-wrong-metadata`  to check if this fixes your issue?

```
pip install -U --user https://github.com/goldmann/docker-squash/archive/gh-91-wrong-metadata.zip
```

**Comment by twaugh** [comment]
Works for me. Thanks!
